"""Generates a fictitious-but-plausible dataset for the MVP Vasco demo.

Populates:
  - Postgres (Identity layer): club, person, fan, membership
  - Neo4j (Knowledge Graph): Club, Team, Player, Venue, Competition, Season,
    Match, Fan, FanProfile, ChurnRisk, FanSegment, Ticket + relationships

Personal data (name, email, phone) is generated by Faker and IMMEDIATELY
hashed with PII_HASH_SALT before it touches either database — per the
"dados pessoais sempre hasheados desde o dia 1" principle in CLAUDE.md.
Nothing here is real club data; fields the ontology marks `[confirmar]`
are either omitted or filled with an obviously-fake placeholder.

Writes are batched (bulk Postgres inserts, UNWIND-based Neo4j writes) and
committed in chunks rather than one giant transaction — this dataset was
originally written record-by-record and lost all ~500 fans when a single
dropped connection rolled back the one final commit. Batching also cuts
this from ~4500 individual round trips to a few dozen.

Run inside the backend container:
    docker compose exec backend python -m database.seed.seed
"""

import hashlib
import os
import random
import uuid
from datetime import timedelta, datetime, timezone

from faker import Faker

from backend import models
from backend.database import Base, SessionLocal, engine
from backend.graph.neo4j_client import run_query

fake = Faker("pt_BR")
Faker.seed(42)
random.seed(42)

PII_SALT = os.environ.get("PII_HASH_SALT", "dev-only-change-me")

N_FANS = 500
N_PLAYERS = 23
N_MATCHES = 10
CHUNK_SIZE = 100


def pii_hash(value: str) -> str:
    return hashlib.sha256(f"{PII_SALT}:{value}".encode()).hexdigest()


def chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def build_fan_rows():
    """Pure-Python generation of all rows, no DB access yet."""
    club_id = uuid.uuid4()
    person_rows, fan_rows, membership_rows = [], [], []
    fans_summary = []

    for _ in range(N_FANS):
        person_id = uuid.uuid4()
        fan_id = uuid.uuid4()
        fan_since = fake.date_between(start_date="-10y", end_date="-1m")

        person_rows.append(
            {
                "id": person_id,
                "full_name_hash": pii_hash(fake.name()),
                "email_hash": pii_hash(fake.email()),
                "phone_hash": pii_hash(fake.phone_number()),
                "birth_date": fake.date_of_birth(minimum_age=14, maximum_age=80),
                "city": fake.city(),
                "state": "RJ",
                "country": "BR",
                "source_systems": ["seed_fixture"],
            }
        )
        fan_rows.append(
            {
                "id": fan_id,
                "person_id": person_id,
                "fan_since": fan_since,
                "lifetime_value": round(random.uniform(50, 8000), 2),
                "acquisition_channel": random.choice(
                    ["organic", "campaign", "referral"]
                ),
            }
        )

        membership_id = None
        membership_status = None
        if random.random() < 0.7:
            membership_id = uuid.uuid4()
            membership_status = random.choices(
                ["active", "cancelled", "expired"], weights=[0.75, 0.15, 0.10]
            )[0]
            started_at = fake.date_between(start_date=fan_since, end_date="today")
            membership_rows.append(
                {
                    "id": membership_id,
                    "fan_id": fan_id,
                    "plan_name": random.choice(
                        ["Basico", "Prata", "Ouro", "Patrimonial"]
                    ),
                    "status": membership_status,
                    "monthly_value": round(random.uniform(29.9, 249.9), 2),
                    "started_at": started_at,
                    "renews_at": started_at + timedelta(days=365),
                    "cancelled_at": fake.date_between(
                        start_date=started_at, end_date="today"
                    )
                    if membership_status == "cancelled"
                    else None,
                }
            )

        fans_summary.append(
            {
                "fan_id": fan_id,
                "membership_id": membership_id,
                "membership_status": membership_status,
            }
        )

    return club_id, person_rows, fan_rows, membership_rows, fans_summary


def seed_postgres(club_id, person_rows, fan_rows, membership_rows):
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        db.execute(
            models.Club.__table__.insert(),
            [
                {
                    "id": club_id,
                    "name": "Club de Regatas Vasco da Gama",
                    "short_name": "Vasco",
                    "founded_year": "1898",
                    "primary_color": "black-white",
                    "crest_url": "https://example.invalid/crest/vasco.png",
                }
            ],
        )
        db.commit()
        print("Club criado.")

        for i, chunk in enumerate(chunks(person_rows, CHUNK_SIZE)):
            db.execute(models.Person.__table__.insert(), chunk)
            db.commit()
            print(f"  person chunk {i + 1} ({len(chunk)} rows) commitado.")

        for i, chunk in enumerate(chunks(fan_rows, CHUNK_SIZE)):
            db.execute(models.Fan.__table__.insert(), chunk)
            db.commit()
            print(f"  fan chunk {i + 1} ({len(chunk)} rows) commitado.")

        for i, chunk in enumerate(chunks(membership_rows, CHUNK_SIZE)):
            db.execute(models.Membership.__table__.insert(), chunk)
            db.commit()
            print(f"  membership chunk {i + 1} ({len(chunk)} rows) commitado.")
    finally:
        db.close()


def seed_graph_sport(club_id) -> tuple[str, list[str]]:
    run_query(
        "MERGE (c:Club {id: $id}) SET c.name = $name, c.short_name = $short_name",
        id=str(club_id),
        name="Club de Regatas Vasco da Gama",
        short_name="Vasco",
    )

    team_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (t:Team {id: $id})
        SET t.name = 'Vasco da Gama', t.category = 'pro_men'
        WITH t
        MATCH (c:Club {id: $club_id})
        MERGE (t)-[:PART_OF]->(c)
        """,
        id=team_id,
        club_id=str(club_id),
    )

    player_rows = [
        {
            "id": str(uuid.uuid4()),
            "name": fake.name(),
            "position": random.choice(["GOL", "ZAG", "LAT", "VOL", "MEI", "ATA"]),
            "number": random.randint(1, 99),
        }
        for _ in range(N_PLAYERS)
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (p:Player {id: row.id})
        SET p.full_name = row.name, p.position = row.position, p.shirt_number = row.number
        WITH p
        MATCH (t:Team {id: $team_id})
        MERGE (p)-[:PLAYS_FOR]->(t)
        """,
        rows=player_rows,
        team_id=team_id,
    )

    venue_id = str(uuid.uuid4())
    run_query(
        "MERGE (v:Venue {id: $id}) SET v.name = 'Sao Januario', v.city = 'Rio de Janeiro', v.capacity = 21880",
        id=venue_id,
    )
    competition_id = str(uuid.uuid4())
    run_query(
        "MERGE (comp:Competition {id: $id}) SET comp.name = 'Brasileirao Serie A'",
        id=competition_id,
    )
    season_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (s:Season {id: $id})
        SET s.year = 2026, s.start_date = date('2026-04-01'), s.end_date = date('2026-12-01')
        WITH s
        MATCH (comp:Competition {id: $competition_id})
        MERGE (s)-[:EDITION_OF]->(comp)
        """,
        id=season_id,
        competition_id=competition_id,
    )

    match_ids = []
    match_rows = []
    for i in range(N_MATCHES):
        match_id = str(uuid.uuid4())
        match_ids.append(match_id)
        scheduled_at = datetime.now(timezone.utc) - timedelta(days=(N_MATCHES - i) * 7)
        match_rows.append(
            {
                "id": match_id,
                "scheduled_at": scheduled_at.isoformat(),
                "home_score": random.randint(0, 4),
                "away_score": random.randint(0, 4),
            }
        )
    run_query(
        """
        UNWIND $rows AS row
        MERGE (m:Match {id: row.id})
        SET m.scheduled_at = datetime(row.scheduled_at), m.status = 'finished',
            m.home_score = row.home_score, m.away_score = row.away_score
        WITH m
        MATCH (t:Team {id: $team_id}), (v:Venue {id: $venue_id}), (s:Season {id: $season_id})
        MERGE (m)-[:PART_OF]->(s)
        MERGE (m)-[:HELD_AT]->(v)
        MERGE (m)-[:HOME_TEAM]->(t)
        """,
        rows=match_rows,
        team_id=team_id,
        venue_id=venue_id,
        season_id=season_id,
    )

    print(f"Grafo esportivo criado: 1 team, {N_PLAYERS} players, {N_MATCHES} matches.")
    return team_id, match_ids


def seed_graph_fans(fans_summary: list[dict], match_ids: list[str]) -> None:
    profile_rows = []
    ticket_rows = []
    membership_rows = []
    risk_rows = []
    segment_rows = []

    for entry in fans_summary:
        fan_id = str(entry["fan_id"])
        engagement_score = round(random.uniform(0, 1), 2)
        matches_attended = random.randint(0, len(match_ids))

        profile_rows.append(
            {
                "fan_id": fan_id,
                "engagement_score": engagement_score,
                "matches_attended": matches_attended,
            }
        )

        for m_id in random.sample(match_ids, k=min(matches_attended, len(match_ids))):
            ticket_rows.append({"fan_id": fan_id, "match_id": m_id})

        if entry["membership_id"] and entry["membership_status"] == "active":
            mid = str(entry["membership_id"])
            membership_rows.append(
                {"mid": mid, "status": entry["membership_status"], "fan_id": fan_id}
            )

            risk_score = round(
                max(0.0, min(1.0, (1 - engagement_score) * random.uniform(0.6, 1.1))), 2
            )
            if risk_score >= 0.5:
                risk_rows.append({"mid": mid, "risk_score": risk_score})

        if engagement_score > 0.8:
            segment_rows.append({"fan_id": fan_id, "seg_name": "socios_alto_valor"})

    for i, chunk in enumerate(chunks(profile_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (f:Fan {id: row.fan_id})
            MERGE (fp:FanProfile {id: row.fan_id + '-profile'})
            SET fp.engagement_score = row.engagement_score,
                fp.matches_attended_count = row.matches_attended,
                fp.updated_at = datetime()
            MERGE (fp)-[:PROFILE_OF]->(f)
            """,
            rows=chunk,
        )
        print(f"  fan/profile chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(ticket_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MATCH (f:Fan {id: row.fan_id}), (m:Match {id: row.match_id})
            MERGE (t:Ticket {id: randomUUID()})
            MERGE (t)-[:ADMITS_TO]->(m)
            MERGE (t)-[:HELD_BY]->(f)
            """,
            rows=chunk,
        )
        print(f"  ticket chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(membership_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (m:Membership {id: row.mid}) SET m.status = row.status
            WITH m, row
            MATCH (f:Fan {id: row.fan_id})
            MERGE (f)-[:HAS_MEMBERSHIP]->(m)
            """,
            rows=chunk,
        )
        print(f"  membership-edge chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(risk_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MATCH (m:Membership {id: row.mid})
            MERGE (cr:ChurnRisk {id: row.mid + '-risk'})
            SET cr.risk_score = row.risk_score,
                cr.reason_codes = ['baixo_engajamento'],
                cr.calculated_at = datetime()
            MERGE (cr)-[:RISK_OF]->(m)
            """,
            rows=chunk,
        )
        print(f"  churn-risk chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(segment_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (seg:FanSegment {id: 'segment-' + row.seg_name})
            SET seg.name = row.seg_name, seg.definition_rule = 'engagement_score > 0.8'
            WITH seg, row
            MATCH (f:Fan {id: row.fan_id})
            MERGE (f)-[:BELONGS_TO_SEGMENT]->(seg)
            """,
            rows=chunk,
        )
        print(f"  segment chunk {i + 1} ({len(chunk)} rows) gravado.")


def main():
    club_id, person_rows, fan_rows, membership_rows, fans_summary = build_fan_rows()

    seed_postgres(club_id, person_rows, fan_rows, membership_rows)
    _, match_ids = seed_graph_sport(club_id)
    seed_graph_fans(fans_summary, match_ids)

    print(f"Seed completo. club_id={club_id}")
    print(f"{len(fans_summary)} fans criados (Postgres + Neo4j).")


if __name__ == "__main__":
    main()
