"""Generates a fictitious-but-plausible dataset for the MVP Vasco demo.

Populates:
  - Postgres (Identity layer): club, person, fan, membership
  - Neo4j (Knowledge Graph): Club, Team, Player, Venue, Competition, Season,
    Match, Fan, FanProfile, ChurnRisk, FanSegment, Ticket + relationships

Personal data (name, email, phone) is generated by Faker and IMMEDIATELY
hashed with PII_HASH_SALT before it touches either database — per the
"dados pessoais sempre hasheados desde o dia 1" principle in CLAUDE.md.
Nothing here is real club data; fields the ontology marks `[confirmar]`
are either omitted or filled with an obviously-fake placeholder.

Run inside the backend container:
    docker compose exec backend python -m database.seed.seed
"""

import hashlib
import os
import random
import uuid
from datetime import date, datetime, timedelta, timezone

from faker import Faker
from sqlalchemy.orm import Session

from backend import models
from backend.database import Base, SessionLocal, engine
from backend.graph.neo4j_client import run_query

fake = Faker("pt_BR")
Faker.seed(42)
random.seed(42)

PII_SALT = os.environ.get("PII_HASH_SALT", "dev-only-change-me")

N_FANS = 500
N_PLAYERS = 23
N_MATCHES = 10


def pii_hash(value: str) -> str:
    return hashlib.sha256(f"{PII_SALT}:{value}".encode()).hexdigest()


def seed_postgres(db: Session) -> tuple[uuid.UUID, list[dict]]:
    Base.metadata.create_all(bind=engine)

    club = models.Club(
        name="Club de Regatas Vasco da Gama",
        short_name="Vasco",
        founded_year="1898",
        primary_color="black-white",
        crest_url="https://example.invalid/crest/vasco.png",
    )
    db.add(club)
    db.flush()

    fans_summary = []
    for _ in range(N_FANS):
        name = fake.name()
        person = models.Person(
            full_name_hash=pii_hash(name),
            email_hash=pii_hash(fake.email()),
            phone_hash=pii_hash(fake.phone_number()),
            birth_date=fake.date_of_birth(minimum_age=14, maximum_age=80),
            city=fake.city(),
            state="RJ",
            country="BR",
            source_systems=["seed_fixture"],
        )
        db.add(person)
        db.flush()

        fan_since = fake.date_between(start_date="-10y", end_date="-1m")
        fan = models.Fan(
            person_id=person.id,
            fan_since=fan_since,
            lifetime_value=round(random.uniform(50, 8000), 2),
            acquisition_channel=random.choice(["organic", "campaign", "referral"]),
        )
        db.add(fan)
        db.flush()

        has_membership = random.random() < 0.7
        membership = None
        if has_membership:
            status = random.choices(
                ["active", "cancelled", "expired"], weights=[0.75, 0.15, 0.10]
            )[0]
            started_at = fake.date_between(start_date=fan_since, end_date="today")
            renews_at = started_at + timedelta(days=365)
            membership = models.Membership(
                fan_id=fan.id,
                plan_name=random.choice(["Basico", "Prata", "Ouro", "Patrimonial"]),
                status=status,
                monthly_value=round(random.uniform(29.9, 249.9), 2),
                started_at=started_at,
                renews_at=renews_at,
                cancelled_at=fake.date_between(start_date=started_at, end_date="today")
                if status == "cancelled"
                else None,
            )
            db.add(membership)
            db.flush()

        fans_summary.append(
            {
                "fan_id": fan.id,
                "membership_id": membership.id if membership else None,
                "membership_status": membership.status if membership else None,
            }
        )

    db.commit()
    return club.id, fans_summary


def seed_graph(club_id: uuid.UUID, fans_summary: list[dict]) -> None:
    run_query(
        "MERGE (c:Club {id: $id}) SET c.name = $name, c.short_name = $short_name",
        id=str(club_id),
        name="Club de Regatas Vasco da Gama",
        short_name="Vasco",
    )

    team_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (t:Team {id: $id})
        SET t.name = 'Vasco da Gama', t.category = 'pro_men'
        WITH t
        MATCH (c:Club {id: $club_id})
        MERGE (t)-[:PART_OF]->(c)
        """,
        id=team_id,
        club_id=str(club_id),
    )

    for _ in range(N_PLAYERS):
        run_query(
            """
            MERGE (p:Player {id: $id})
            SET p.full_name = $name, p.position = $position,
                p.shirt_number = $number
            WITH p
            MATCH (t:Team {id: $team_id})
            MERGE (p)-[:PLAYS_FOR]->(t)
            """,
            id=str(uuid.uuid4()),
            name=fake.name(),
            position=random.choice(["GOL", "ZAG", "LAT", "VOL", "MEI", "ATA"]),
            number=random.randint(1, 99),
            team_id=team_id,
        )

    venue_id = str(uuid.uuid4())
    run_query(
        "MERGE (v:Venue {id: $id}) SET v.name = 'Sao Januario', v.city = 'Rio de Janeiro', v.capacity = 21880",
        id=venue_id,
    )
    competition_id = str(uuid.uuid4())
    run_query(
        "MERGE (comp:Competition {id: $id}) SET comp.name = 'Brasileirao Serie A'",
        id=competition_id,
    )
    season_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (s:Season {id: $id})
        SET s.year = 2026, s.start_date = date('2026-04-01'), s.end_date = date('2026-12-01')
        WITH s
        MATCH (comp:Competition {id: $competition_id})
        MERGE (s)-[:EDITION_OF]->(comp)
        """,
        id=season_id,
        competition_id=competition_id,
    )

    match_ids = []
    for i in range(N_MATCHES):
        match_id = str(uuid.uuid4())
        match_ids.append(match_id)
        scheduled_at = datetime.now(timezone.utc) - timedelta(days=(N_MATCHES - i) * 7)
        run_query(
            """
            MERGE (m:Match {id: $id})
            SET m.scheduled_at = datetime($scheduled_at), m.status = 'finished',
                m.home_score = $home_score, m.away_score = $away_score
            WITH m
            MATCH (t:Team {id: $team_id}), (v:Venue {id: $venue_id}), (s:Season {id: $season_id})
            MERGE (m)-[:PART_OF]->(s)
            MERGE (m)-[:HELD_AT]->(v)
            MERGE (m)-[:HOME_TEAM]->(t)
            """,
            id=match_id,
            scheduled_at=scheduled_at.isoformat(),
            home_score=random.randint(0, 4),
            away_score=random.randint(0, 4),
            team_id=team_id,
            venue_id=venue_id,
            season_id=season_id,
        )

    for entry in fans_summary:
        fan_id = str(entry["fan_id"])
        engagement_score = round(random.uniform(0, 1), 2)
        matches_attended = random.randint(0, N_MATCHES)

        run_query(
            """
            MERGE (f:Fan {id: $fan_id})
            MERGE (fp:FanProfile {id: $fan_id + '-profile'})
            SET fp.engagement_score = $engagement_score,
                fp.matches_attended_count = $matches_attended,
                fp.updated_at = datetime()
            MERGE (fp)-[:PROFILE_OF]->(f)
            """,
            fan_id=fan_id,
            engagement_score=engagement_score,
            matches_attended=matches_attended,
        )

        attended = random.sample(match_ids, k=min(matches_attended, len(match_ids)))
        for m_id in attended:
            run_query(
                """
                MATCH (f:Fan {id: $fan_id}), (m:Match {id: $match_id})
                MERGE (t:Ticket {id: randomUUID()})
                MERGE (t)-[:ADMITS_TO]->(m)
                MERGE (t)-[:HELD_BY]->(f)
                """,
                fan_id=fan_id,
                match_id=m_id,
            )

        if entry["membership_id"] and entry["membership_status"] == "active":
            run_query(
                "MERGE (m:Membership {id: $mid}) SET m.status = $status "
                "WITH m MATCH (f:Fan {id: $fan_id}) MERGE (f)-[:HAS_MEMBERSHIP]->(m)",
                mid=str(entry["membership_id"]),
                status=entry["membership_status"],
                fan_id=fan_id,
            )

            risk_score = round(
                max(0.0, min(1.0, (1 - engagement_score) * random.uniform(0.6, 1.1))), 2
            )
            if risk_score >= 0.5:
                run_query(
                    """
                    MATCH (m:Membership {id: $mid})
                    MERGE (cr:ChurnRisk {id: $mid + '-risk'})
                    SET cr.risk_score = $risk_score,
                        cr.reason_codes = ['baixo_engajamento'],
                        cr.calculated_at = datetime()
                    MERGE (cr)-[:RISK_OF]->(m)
                    """,
                    mid=str(entry["membership_id"]),
                    risk_score=risk_score,
                )

        if entry["fan_id"]:
            segment_name = (
                "socios_alto_valor" if engagement_score > 0.8 else None
            )
            if segment_name:
                run_query(
                    """
                    MERGE (seg:FanSegment {id: $seg_id})
                    SET seg.name = $seg_name, seg.definition_rule = 'engagement_score > 0.8'
                    WITH seg
                    MATCH (f:Fan {id: $fan_id})
                    MERGE (f)-[:BELONGS_TO_SEGMENT]->(seg)
                    """,
                    seg_id=f"segment-{segment_name}",
                    seg_name=segment_name,
                    fan_id=fan_id,
                )


def main():
    db = SessionLocal()
    try:
        club_id, fans_summary = seed_postgres(db)
    finally:
        db.close()

    seed_graph(club_id, fans_summary)

    print(f"Seed completo. club_id={club_id}")
    print(f"{len(fans_summary)} fans criados (Postgres + Neo4j).")


if __name__ == "__main__":
    main()
