"""Generates a fictitious-but-plausible dataset for the MVP Vasco demo.

Populates:
  - Postgres (Identity layer): club, person, fan, membership
  - Neo4j (Knowledge Graph): Club, Team, Player, Venue, Competition, Season,
    Match, Fan, FanProfile, ChurnRisk, FanSegment, Ticket + relationships

Personal data (name, email, phone) is generated by Faker and IMMEDIATELY
hashed with PII_HASH_SALT before it touches either database — per the
"dados pessoais sempre hasheados desde o dia 1" principle in CLAUDE.md.
Nothing here is real club data; fields the ontology marks `[confirmar]`
are either omitted or filled with an obviously-fake placeholder.

Writes are batched (bulk Postgres inserts, UNWIND-based Neo4j writes) and
committed in chunks rather than one giant transaction — this dataset was
originally written record-by-record and lost all ~500 fans when a single
dropped connection rolled back the one final commit. Batching also cuts
this from ~4500 individual round trips to a few dozen.

Run inside the backend container:
    docker compose exec backend python -m database.seed.seed
"""

import hashlib
import os
import random
import uuid
from datetime import timedelta, datetime, timezone

from faker import Faker

from backend import models
from backend.database import Base, SessionLocal, engine
from backend.graph.neo4j_client import run_query

fake = Faker("pt_BR")
Faker.seed(42)
random.seed(42)

PII_SALT = os.environ.get("PII_HASH_SALT", "dev-only-change-me")

N_FANS = 500
N_PLAYERS = 23
N_MATCHES = 10
CHUNK_SIZE = 100


def pii_hash(value: str) -> str:
    return hashlib.sha256(f"{PII_SALT}:{value}".encode()).hexdigest()


def chunks(seq, size):
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def build_fan_rows():
    """Pure-Python generation of all rows, no DB access yet."""
    club_id = uuid.uuid4()
    person_rows, fan_rows, membership_rows = [], [], []
    fans_summary = []

    for _ in range(N_FANS):
        person_id = uuid.uuid4()
        fan_id = uuid.uuid4()
        fan_since = fake.date_between(start_date="-10y", end_date="-1m")

        person_rows.append(
            {
                "id": person_id,
                "full_name_hash": pii_hash(fake.name()),
                "email_hash": pii_hash(fake.email()),
                "phone_hash": pii_hash(fake.phone_number()),
                "birth_date": fake.date_of_birth(minimum_age=14, maximum_age=80),
                "city": fake.city(),
                "state": "RJ",
                "country": "BR",
                "source_systems": ["seed_fixture"],
            }
        )
        fan_rows.append(
            {
                "id": fan_id,
                "person_id": person_id,
                "fan_since": fan_since,
                "lifetime_value": round(random.uniform(50, 8000), 2),
                "acquisition_channel": random.choice(
                    ["organic", "campaign", "referral"]
                ),
            }
        )

        membership_id = None
        membership_status = None
        if random.random() < 0.7:
            membership_id = uuid.uuid4()
            membership_status = random.choices(
                ["active", "cancelled", "expired"], weights=[0.75, 0.15, 0.10]
            )[0]
            started_at = fake.date_between(start_date=fan_since, end_date="today")
            membership_rows.append(
                {
                    "id": membership_id,
                    "fan_id": fan_id,
                    "plan_name": random.choice(
                        ["Basico", "Prata", "Ouro", "Patrimonial"]
                    ),
                    "status": membership_status,
                    "monthly_value": round(random.uniform(29.9, 249.9), 2),
                    "started_at": started_at,
                    "renews_at": started_at + timedelta(days=365),
                    "cancelled_at": fake.date_between(
                        start_date=started_at, end_date="today"
                    )
                    if membership_status == "cancelled"
                    else None,
                }
            )

        fans_summary.append(
            {
                "fan_id": fan_id,
                "membership_id": membership_id,
                "membership_status": membership_status,
            }
        )

    return club_id, person_rows, fan_rows, membership_rows, fans_summary


def seed_postgres(club_id, person_rows, fan_rows, membership_rows):
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        db.execute(
            models.Club.__table__.insert(),
            [
                {
                    "id": club_id,
                    "name": "Club de Regatas Vasco da Gama",
                    "short_name": "Vasco",
                    "founded_year": "1898",
                    "primary_color": "black-white",
                    "crest_url": "https://example.invalid/crest/vasco.png",
                }
            ],
        )
        db.commit()
        print("Club criado.")

        for i, chunk in enumerate(chunks(person_rows, CHUNK_SIZE)):
            db.execute(models.Person.__table__.insert(), chunk)
            db.commit()
            print(f"  person chunk {i + 1} ({len(chunk)} rows) commitado.")

        for i, chunk in enumerate(chunks(fan_rows, CHUNK_SIZE)):
            db.execute(models.Fan.__table__.insert(), chunk)
            db.commit()
            print(f"  fan chunk {i + 1} ({len(chunk)} rows) commitado.")

        for i, chunk in enumerate(chunks(membership_rows, CHUNK_SIZE)):
            db.execute(models.Membership.__table__.insert(), chunk)
            db.commit()
            print(f"  membership chunk {i + 1} ({len(chunk)} rows) commitado.")
    finally:
        db.close()


def seed_graph_sport(club_id) -> tuple[str, list[str]]:
    run_query(
        "MERGE (c:Club {id: $id}) SET c.name = $name, c.short_name = $short_name",
        id=str(club_id),
        name="Club de Regatas Vasco da Gama",
        short_name="Vasco",
    )

    team_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (t:Team {id: $id})
        SET t.name = 'Vasco da Gama', t.category = 'pro_men'
        WITH t
        MATCH (c:Club {id: $club_id})
        MERGE (t)-[:PART_OF]->(c)
        """,
        id=team_id,
        club_id=str(club_id),
    )

    player_rows = [
        {
            "id": str(uuid.uuid4()),
            "name": fake.name(),
            "position": random.choice(["GOL", "ZAG", "LAT", "VOL", "MEI", "ATA"]),
            "number": random.randint(1, 99),
        }
        for _ in range(N_PLAYERS)
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (p:Player {id: row.id})
        SET p.full_name = row.name, p.position = row.position, p.shirt_number = row.number
        WITH p
        MATCH (t:Team {id: $team_id})
        MERGE (p)-[:PLAYS_FOR]->(t)
        """,
        rows=player_rows,
        team_id=team_id,
    )

    venue_id = str(uuid.uuid4())
    run_query(
        "MERGE (v:Venue {id: $id}) SET v.name = 'Sao Januario', v.city = 'Rio de Janeiro', v.capacity = 21880",
        id=venue_id,
    )
    competition_id = str(uuid.uuid4())
    run_query(
        "MERGE (comp:Competition {id: $id}) SET comp.name = 'Brasileirao Serie A'",
        id=competition_id,
    )
    season_id = str(uuid.uuid4())
    run_query(
        """
        MERGE (s:Season {id: $id})
        SET s.year = 2026, s.start_date = date('2026-04-01'), s.end_date = date('2026-12-01')
        WITH s
        MATCH (comp:Competition {id: $competition_id})
        MERGE (s)-[:EDITION_OF]->(comp)
        """,
        id=season_id,
        competition_id=competition_id,
    )

    match_ids = []
    match_rows = []
    for i in range(N_MATCHES):
        match_id = str(uuid.uuid4())
        match_ids.append(match_id)
        scheduled_at = datetime.now(timezone.utc) - timedelta(days=(N_MATCHES - i) * 7)
        match_rows.append(
            {
                "id": match_id,
                "scheduled_at": scheduled_at.isoformat(),
                "home_score": random.randint(0, 4),
                "away_score": random.randint(0, 4),
            }
        )
    run_query(
        """
        UNWIND $rows AS row
        MERGE (m:Match {id: row.id})
        SET m.scheduled_at = datetime(row.scheduled_at), m.status = 'finished',
            m.home_score = row.home_score, m.away_score = row.away_score
        WITH m
        MATCH (t:Team {id: $team_id}), (v:Venue {id: $venue_id}), (s:Season {id: $season_id})
        MERGE (m)-[:PART_OF]->(s)
        MERGE (m)-[:HELD_AT]->(v)
        MERGE (m)-[:HOME_TEAM]->(t)
        """,
        rows=match_rows,
        team_id=team_id,
        venue_id=venue_id,
        season_id=season_id,
    )

    print(f"Grafo esportivo criado: 1 team, {N_PLAYERS} players, {N_MATCHES} matches.")
    return team_id, match_ids


def seed_graph_fans(fans_summary: list[dict], match_ids: list[str]) -> None:
    profile_rows = []
    ticket_rows = []
    membership_rows = []
    risk_rows = []
    segment_rows = []

    for entry in fans_summary:
        fan_id = str(entry["fan_id"])
        engagement_score = round(random.uniform(0, 1), 2)
        matches_attended = random.randint(0, len(match_ids))

        profile_rows.append(
            {
                "fan_id": fan_id,
                "engagement_score": engagement_score,
                "matches_attended": matches_attended,
            }
        )

        for m_id in random.sample(match_ids, k=min(matches_attended, len(match_ids))):
            ticket_rows.append({"fan_id": fan_id, "match_id": m_id})

        if entry["membership_id"] and entry["membership_status"] == "active":
            mid = str(entry["membership_id"])
            membership_rows.append(
                {"mid": mid, "status": entry["membership_status"], "fan_id": fan_id}
            )

            risk_score = round(
                max(0.0, min(1.0, (1 - engagement_score) * random.uniform(0.6, 1.1))), 2
            )
            if risk_score >= 0.5:
                risk_rows.append({"mid": mid, "risk_score": risk_score})

        if engagement_score > 0.8:
            segment_rows.append({"fan_id": fan_id, "seg_name": "socios_alto_valor"})

    for i, chunk in enumerate(chunks(profile_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (f:Fan {id: row.fan_id})
            MERGE (fp:FanProfile {id: row.fan_id + '-profile'})
            SET fp.engagement_score = row.engagement_score,
                fp.matches_attended_count = row.matches_attended,
                fp.updated_at = datetime()
            MERGE (fp)-[:PROFILE_OF]->(f)
            """,
            rows=chunk,
        )
        print(f"  fan/profile chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(ticket_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MATCH (f:Fan {id: row.fan_id}), (m:Match {id: row.match_id})
            MERGE (t:Ticket {id: randomUUID()})
            MERGE (t)-[:ADMITS_TO]->(m)
            MERGE (t)-[:HELD_BY]->(f)
            """,
            rows=chunk,
        )
        print(f"  ticket chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(membership_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (m:Membership {id: row.mid}) SET m.status = row.status
            WITH m, row
            MATCH (f:Fan {id: row.fan_id})
            MERGE (f)-[:HAS_MEMBERSHIP]->(m)
            """,
            rows=chunk,
        )
        print(f"  membership-edge chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(risk_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MATCH (m:Membership {id: row.mid})
            MERGE (cr:ChurnRisk {id: row.mid + '-risk'})
            SET cr.risk_score = row.risk_score,
                cr.reason_codes = ['baixo_engajamento'],
                cr.calculated_at = datetime()
            MERGE (cr)-[:RISK_OF]->(m)
            """,
            rows=chunk,
        )
        print(f"  churn-risk chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(segment_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (seg:FanSegment {id: 'segment-' + row.seg_name})
            SET seg.name = row.seg_name, seg.definition_rule = 'engagement_score > 0.8'
            WITH seg, row
            MATCH (f:Fan {id: row.fan_id})
            MERGE (f)-[:BELONGS_TO_SEGMENT]->(seg)
            """,
            rows=chunk,
        )
        print(f"  segment chunk {i + 1} ({len(chunk)} rows) gravado.")


SPONSOR_NAMES = [
    ("Vetor Seguros", "insurance"),
    ("Litoral Bank", "finance"),
    ("Andina Bebidas", "beverages"),
    ("Praxis Tech", "technology"),
]

PRODUCT_CATALOG = [
    ("Camisa I 2026", "jersey"),
    ("Camisa II 2026", "jersey"),
    ("Camisa III 2026", "jersey"),
    ("Camisa Retro 1998", "jersey"),
    ("Bone Vasco", "accessory"),
    ("Cachecol Vasco", "accessory"),
    ("Mochila Vasco", "accessory"),
    ("Caneca Vasco", "accessory"),
]

SOCIAL_PLATFORMS = ["instagram", "tiktok", "x", "youtube"]
CONTENT_TYPES = ["post", "video", "story", "live"]
INTERACTION_TYPES = ["view", "like", "comment", "share"]


def seed_graph_commercial(club_id: uuid.UUID) -> None:
    sponsor_rows = [
        {"id": str(uuid.uuid4()), "name": name, "industry": industry, "tier": tier}
        for (name, industry), tier in zip(
            SPONSOR_NAMES, ["master", "official", "official", "supporter"]
        )
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (s:Sponsor {id: row.id})
        SET s.name = row.name, s.industry = row.industry, s.tier = row.tier
        """,
        rows=sponsor_rows,
    )

    contract_rows = []
    for sponsor in sponsor_rows:
        starts_at = fake.date_between(start_date="-2y", end_date="-6m")
        contract_rows.append(
            {
                "id": str(uuid.uuid4()),
                "sponsor_id": sponsor["id"],
                "annual_value": round(random.uniform(500_000, 8_000_000), 2),
                "starts_at": starts_at.isoformat(),
                "ends_at": (starts_at + timedelta(days=730)).isoformat(),
            }
        )
    run_query(
        """
        UNWIND $rows AS row
        MERGE (c:SponsorshipContract {id: row.id})
        SET c.annual_value = row.annual_value,
            c.starts_at = date(row.starts_at), c.ends_at = date(row.ends_at)
        WITH c, row
        MATCH (s:Sponsor {id: row.sponsor_id}), (club:Club {id: $club_id})
        MERGE (c)-[:CONTRACT_OF]->(s)
        MERGE (c)-[:SPONSORS]->(club)
        """,
        rows=contract_rows,
        club_id=str(club_id),
    )

    activation_rows = [
        {
            "id": str(uuid.uuid4()),
            "contract_id": contract["id"],
            "activation_type": random.choice(
                ["post_patrocinado", "experiencia_em_jogo", "naming_arena"]
            ),
            "occurred_at": fake.date_time_between(
                start_date="-6m", end_date="now"
            ).isoformat(),
        }
        for contract in contract_rows
        for _ in range(random.randint(1, 3))
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (a:SponsorActivation {id: row.id})
        SET a.activation_type = row.activation_type, a.occurred_at = datetime(row.occurred_at)
        WITH a, row
        MATCH (c:SponsorshipContract {id: row.contract_id})
        MERGE (a)-[:ACTIVATES]->(c)
        """,
        rows=activation_rows,
    )

    print(
        f"Commercial: {len(sponsor_rows)} sponsors, {len(contract_rows)} contracts, "
        f"{len(activation_rows)} activations."
    )


def seed_graph_commerce(fans_summary: list[dict]) -> None:
    product_rows = [
        {
            "id": str(uuid.uuid4()),
            "sku": f"VASCO-{i:04d}",
            "name": name,
            "category": category,
            "price": round(random.uniform(59.9, 349.9), 2),
        }
        for i, (name, category) in enumerate(PRODUCT_CATALOG, start=1)
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (p:Product {id: row.id})
        SET p.sku = row.sku, p.name = row.name, p.category = row.category, p.price = row.price
        """,
        rows=product_rows,
    )

    order_rows = []
    item_rows = []
    buyers = random.sample(fans_summary, k=int(len(fans_summary) * 0.4))
    for entry in buyers:
        for _ in range(random.randint(1, 2)):
            order_id = str(uuid.uuid4())
            items = random.sample(product_rows, k=random.randint(1, 3))
            total = 0.0
            for product in items:
                qty = random.randint(1, 2)
                total += product["price"] * qty
                item_rows.append(
                    {
                        "id": str(uuid.uuid4()),
                        "order_id": order_id,
                        "product_id": product["id"],
                        "quantity": qty,
                        "unit_price": product["price"],
                    }
                )
            order_rows.append(
                {
                    "id": order_id,
                    "fan_id": str(entry["fan_id"]),
                    "total_value": round(total, 2),
                    "status": random.choices(
                        ["paid", "pending", "refunded"], weights=[0.85, 0.1, 0.05]
                    )[0],
                    "placed_at": fake.date_time_between(
                        start_date="-1y", end_date="now"
                    ).isoformat(),
                }
            )

    for i, chunk in enumerate(chunks(order_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (o:Order {id: row.id})
            SET o.order_type = 'merchandise', o.total_value = row.total_value,
                o.status = row.status, o.placed_at = datetime(row.placed_at)
            WITH o, row
            MATCH (f:Fan {id: row.fan_id})
            MERGE (o)-[:PLACED_BY]->(f)
            """,
            rows=chunk,
        )
        print(f"  order chunk {i + 1} ({len(chunk)} rows) gravado.")

    for i, chunk in enumerate(chunks(item_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MERGE (oi:OrderItem {id: row.id})
            SET oi.quantity = row.quantity, oi.unit_price = row.unit_price
            WITH oi, row
            MATCH (o:Order {id: row.order_id}), (p:Product {id: row.product_id})
            MERGE (oi)-[:LINE_OF]->(o)
            MERGE (oi)-[:FOR_PRODUCT]->(p)
            """,
            rows=chunk,
        )
        print(f"  order-item chunk {i + 1} ({len(chunk)} rows) gravado.")

    print(
        f"Commerce: {len(product_rows)} products, {len(order_rows)} orders, "
        f"{len(item_rows)} order items."
    )


def seed_graph_media(fans_summary: list[dict], match_ids: list[str]) -> None:
    account_rows = [
        {"id": str(uuid.uuid4()), "platform": platform, "handle": f"@vasco.{platform}"}
        for platform in SOCIAL_PLATFORMS
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (sa:SocialAccount {id: row.id})
        SET sa.platform = row.platform, sa.handle = row.handle
        """,
        rows=account_rows,
    )

    content_rows = [
        {
            "id": str(uuid.uuid4()),
            "account_id": random.choice(account_rows)["id"],
            "content_type": random.choice(CONTENT_TYPES),
            "published_at": fake.date_time_between(
                start_date="-6m", end_date="now"
            ).isoformat(),
            "match_id": random.choice(match_ids) if random.random() < 0.5 else None,
        }
        for _ in range(40)
    ]
    run_query(
        """
        UNWIND $rows AS row
        MERGE (mc:MediaContent {id: row.id})
        SET mc.content_type = row.content_type, mc.published_at = datetime(row.published_at)
        WITH mc, row
        MATCH (sa:SocialAccount {id: row.account_id})
        MERGE (mc)-[:PUBLISHED_ON]->(sa)
        WITH mc, row
        OPTIONAL MATCH (m:Match {id: row.match_id})
        FOREACH (_ IN CASE WHEN m IS NOT NULL THEN [1] ELSE [] END | MERGE (mc)-[:ABOUT]->(m))
        """,
        rows=content_rows,
    )

    consumption_rows = []
    consumers = random.sample(fans_summary, k=int(len(fans_summary) * 0.6))
    for entry in consumers:
        for _ in range(random.randint(1, 5)):
            content = random.choice(content_rows)
            consumption_rows.append(
                {
                    "fan_id": str(entry["fan_id"]),
                    "content_id": content["id"],
                    "interaction_type": random.choice(INTERACTION_TYPES),
                    "occurred_at": fake.date_time_between(
                        start_date="-6m", end_date="now"
                    ).isoformat(),
                }
            )

    for i, chunk in enumerate(chunks(consumption_rows, CHUNK_SIZE)):
        run_query(
            """
            UNWIND $rows AS row
            MATCH (f:Fan {id: row.fan_id}), (mc:MediaContent {id: row.content_id})
            MERGE (mcons:MediaConsumption {id: randomUUID()})
            SET mcons.interaction_type = row.interaction_type,
                mcons.occurred_at = datetime(row.occurred_at)
            MERGE (mcons)-[:INTERACTION_WITH]->(mc)
            MERGE (mcons)-[:BY_FAN]->(f)
            """,
            rows=chunk,
        )
        print(f"  media-consumption chunk {i + 1} ({len(chunk)} rows) gravado.")

    print(
        f"Media: {len(account_rows)} social accounts, {len(content_rows)} content "
        f"pieces, {len(consumption_rows)} consumption events."
    )


def main():
    club_id, person_rows, fan_rows, membership_rows, fans_summary = build_fan_rows()

    seed_postgres(club_id, person_rows, fan_rows, membership_rows)
    _, match_ids = seed_graph_sport(club_id)
    seed_graph_fans(fans_summary, match_ids)
    seed_graph_commercial(club_id)
    seed_graph_commerce(fans_summary)
    seed_graph_media(fans_summary, match_ids)

    print(f"Seed completo. club_id={club_id}")
    print(f"{len(fans_summary)} fans criados (Postgres + Neo4j).")


if __name__ == "__main__":
    main()
